public class WinUacControl
{
    public static void EnableUserAccountControl()
    {
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "EnableVirtualization",
            1);
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "EnableInstallerDetection",
            1);
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "PromptOnSecureDesktop",
            1);
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "EnableLUA",
            1);
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "EnableSecureUIAPaths",
            1);
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "ConsentPromptBehaviorAdmin",
            5);
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "ValidateAdminCodeSignatures",
            0);
        WindowsUtils.SetDWord(
          @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
          "EnableUIADesktopToggle",
          0);
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "ConsentPromptBehaviorUser",
            3);
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "FilterAdministratorToken",
            0);
    }

    public static void DisableUserAccountControl()
    {
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "EnableVirtualization",
            0);
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "EnableInstallerDetection",
            0);
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "PromptOnSecureDesktop",
            0);
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "EnableLUA",
            0);
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "EnableSecureUIAPaths",
            0);
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "ConsentPromptBehaviorAdmin",
            0);
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "ValidateAdminCodeSignatures",
            0);
          WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "EnableUIADesktopToggle",
            0);
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "ConsentPromptBehaviorUser",
            0);
        WindowsUtils.SetDWord(
            @"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
            "FilterAdministratorToken",
            0);
    }
}